name: actions-demo

# Controls when the action will run. 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Run jobs sequentially or in parallel
jobs:
  strategy:
    max-parallel: 1
  test:
    name: Unit Test Configuration
    # The type of runner that the job will run on
    runs-on: ubuntu-latest


    # Sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      # Create python env
      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      # Install dependencies to use
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Runs a set of commands using the runners shell
      - name: Run Tests & Coverage
        run: |
          echo Running tests...
          nosetests test/ --with-coverage --cover-package=demo --cover-inclusive --cover-tests --cover-html --cover-html-dir=./coverage

      # Run side-car docker container (e.g. how severn-api uses it)
      - name: Build Docker Image
        uses: docker://amazon/dynamodb-local:1.13.4
        with:
          args: -p 8000:8000

  build:
    name: Build & Publish Docker Image
    runs-on: ubuntu-latest
    steps:
      # Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          # Secrets stored at the directory level
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build image from local Dockerfile and upload to DockerHub
      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: laffeychris/demo_app:latest

      # Echo image name after build
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
