name: actions-demo-simple

# Controls when the action will run. 
# only run on push action
on:
  push:
    branches:
      - main

# Run jobs sequentially or in parallel
jobs:
  test:
    name: Unit Test & Configuration
    # The type of runner that the job will run on
    # Self-hosted runners can be specified by using labels
    runs-on: ubuntu-latest

    # Sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Create python env
      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      # Install dependencies to use
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Runs a set of commands using the runners shell
      - name: Run Tests & Coverage
        run: |
          echo Running tests...
          nosetests test/test_pass.py --with-coverage --cover-package=demo --cover-inclusive --cover-tests --cover-html --cover-html-dir=./coverage

