name: Github Actions Demo

# Controls when the action will run. 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Run jobs sequentially or in parallel
jobs:
  test:
    name: Unit Test configuration
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
